@extends('layouts.app')

@section('title', 'Privacy Policy | Shree Saurashtra Nagrik Sharafi Mandali Ltd.')
@section('meta', 'How Shree Saurashtra Nagrik Sharafi Sahakari Mandali Ltd. handles information collected through this website.')

@section('content')
    <div class="page-head">
        <div class="wrap">
            <p class="crumb"><a href="{{ route('home') }}">Home</a> &rsaquo; Privacy Policy</p>
            <h1>Privacy Policy</h1>
        </div>
    </div>

    <section class="section">
        <div class="wrap">
            <div class="prose reveal">
                
                <p class="updated">Last updated: 28 July 2026</p>
                
                <p>Shree Saurashtra Nagrik Sharafi Sahakari Mandali Ltd., Bagasara (referred to in this policy as &ldquo;the Mandali&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo; or &ldquo;our&rdquo;) respects the privacy of every member, depositor, borrower and visitor. This Privacy Policy explains what information is collected through our website saurashtranagrik.com (the &ldquo;Website&rdquo;), how it is used, and the choices available to you.</p>
                
                <p>By using this Website you agree to the practices described in this policy. Please also read our <a href="{{ route('terms-and-conditions') }}">Terms and Conditions</a>.</p>
                
                <h2>1. About This Website</h2>
                <p>This Website is an informational website only. It provides details of our branches, board of directors, managers, deposit and loan schemes, annual accounts and society activities. The Website does not provide internet banking, mobile banking, online account opening, online payment or any other transactional facility. No enquiry form, login page or payment gateway is offered on this Website.</p>
                
                <h2>2. Information We Collect Through the Website</h2>
                <p>We do not ask you to register, sign in or submit any personal details on this Website. The only information recorded is the technical information that every web server records automatically when a page is requested:</p>
                <ul>
                    <li>IP address of the device or network used to access the Website</li>
                    <li>Date and time of the visit</li>
                    <li>Pages and documents (such as PDF balance sheets) that were opened or downloaded</li>
                    <li>Browser type, operating system and device type</li>
                    <li>The referring page, if you reached us through a link on another website</li>
                </ul>
                <p>These server logs are generated by our hosting provider and are used only for security, troubleshooting and measuring how the Website is used. We do not use them to identify individual visitors.</p>
                
                <h2>3. Information Collected at Our Branches</h2>
                <p>Membership, deposit, loan and other financial services are provided only at our branch offices, through printed application forms and in-person verification. Personal and financial information (such as name, address, contact number, PAN, Aadhaar, KYC documents, photographs, nominee details, income and security details) is collected at the branch and is not collected through this Website. That information is handled in accordance with the bye-laws of the Mandali and applicable law, including the Gujarat Co-operative Societies Act and the rules, circulars and directions issued by the Registrar of Co-operative Societies and the Reserve Bank of India, as applicable.</p>
                
                <h2>4. How We Use Information</h2>
                <ul>
                    <li>To keep the Website secure, available and working correctly</li>
                    <li>To understand which pages and downloads are most useful to visitors</li>
                    <li>To publish statutory and general information about the Mandali, such as annual accounts, progress reports and branch details</li>
                    <li>To comply with legal, statutory, audit and regulatory obligations</li>
                </ul>
                <p>We do not sell, rent or trade any information collected through this Website.</p>
                
                <h2>5. Cookies</h2>
                <p>This Website does not use cookies for advertising, tracking or profiling. Your browser may store standard technical data (such as cached files) to display pages faster. You can clear or block such storage from your browser settings at any time without affecting your ability to read the Website.</p>
                
                <h2>6. Third-Party Services and Links</h2>
                <p>The Website is hosted by a third-party hosting service provider, which maintains the server logs described above on our behalf. The Website may contain links to other websites, including that of our website developer. We are not responsible for the content, security or privacy practices of any external website. We encourage you to read the privacy policy of every website you visit.</p>
                
                <h2>7. Documents Available for Download</h2>
                <p>Balance sheets, profit and loss accounts, progress reports and similar documents published on this Website are statutory or general information documents that are made public by the Mandali. They do not contain individual member account details. Downloading them does not require you to give us any information.</p>
                
                <h2>8. Data Security</h2>
                <p>We take reasonable technical and organisational measures to protect the Website and the information under our control, including secure (HTTPS) delivery of pages and restricted access to our hosting account. However, no method of transmission over the internet is completely secure, and we cannot guarantee absolute security.</p>
                
                <h2>9. Data Retention</h2>
                <p>Server log data is retained by our hosting provider only for as long as needed for security and diagnostic purposes, or for such period as required by law, after which it is deleted or overwritten. Records created at our branches are retained for the period prescribed by the bye-laws of the Mandali and applicable statutory and regulatory requirements.</p>
                
                <h2>10. Children&rsquo;s Privacy</h2>
                <p>This Website is not directed at children. We do not knowingly collect any information from children through this Website. Minor accounts opened at a branch are operated through a parent or legal guardian in accordance with our bye-laws.</p>
                
                <h2>11. Your Rights</h2>
                <p>If you are a member or account holder and wish to know, correct or update the information held about you, please contact the branch where your account is maintained with valid proof of identity. Requests are processed in accordance with our bye-laws and applicable law.</p>
                
                <h2>12. Beware of Fraud</h2>
                <p>The Mandali will never ask you for your account number, PIN, OTP, password or card details by email, SMS, WhatsApp, phone call or through any online form. This Website does not host any login or payment page. If you receive such a request claiming to be from us, do not respond &mdash; please report it to your nearest branch immediately.</p>
                
                <h2>13. Changes to This Policy</h2>
                <p>We may update this Privacy Policy from time to time to reflect changes in our practices or in the law. The revised policy will be published on this page with a new &ldquo;Last updated&rdquo; date. Please review this page periodically.</p>
                
                <h2>14. Contact Us</h2>
                <p>For any question or concern regarding this Privacy Policy, please contact our Head Office:</p>
                <div class="contact-block">
                    <p>
                        <strong>Shree Saurashtra Nagrik Sharafi Sahakari Mandali Ltd.</strong><br>
                        Samarth Saurashtra Building, Amarpara, Bagasara,<br>
                        Dist. Amreli, Gujarat, India
                    </p>
                    <p>
                        Phone: <a href="tel:02796220525">(02796) 220 525</a> &nbsp;|&nbsp; Mobile: <a href="tel:9484529400">94845 29400</a>
                    </p>
                    <p>
                        Website: <a href="{{ route('home') }}">saurashtranagrik.com</a>
                    </p>
                </div>
            </div>
        </div>
    </section>
@endsection
